default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['POSTGRES_USER'] || 'lukesettle' %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  prepared_statements: false

development:
  <<: *default
  database: wanna_watch_dev

test:
  <<: *default
  database: wanna_watch_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
